kind = "web"
previewPath = "/"
title = "Kriczky Virtus"
version = "1.0.0"
id = "artifacts/kriczky-virtus"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23271

[services.development]
run = "pnpm --filter @workspace/kriczky-virtus run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/kriczky-virtus", "run", "build" ]
publicDir = "artifacts/kriczky-virtus/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23271"
BASE_PATH = "/"
